### ISSUE TITLE
Looks like tree shaking does not work

### ISSUE THREAD

**Issue by alexioMark** [pavvell/rxstream#1]
Hey, seems like tree shaking does not work for some reason. I'm trying to import only Subject, but the whole library gets included.

**Comment by pavvell** [comment]
@alexioMark thanks for the feedback! I just released new version with fix, should be fine now. Also, for better tree shaking import things not from the package `import { Subject  } from 'rxstream'` but from particular module, like: `import { Subject  } from 'rxstream/es5/subjects/subject';`
